### ISSUE TITLE
Errors in AbstractCucumberTest

### ISSUE THREAD

**Issue by ramyaw** [lionhearth/cucumber-testng#2]
Hi,

I tried reusing your classes in my project to combine cucumber tests to run with testng.
But I am getting an error when I run my feature through LoginTest.java, Check the logs below, Please let me know if anything strikes quick.

cucumber.runtime.CucumberException: java.lang.reflect.InvocationTargetException
	at cucumber.runtime.io.ClasspathResourceLoader.newInstance(ClasspathResourceLoader.java:80)
	at cucumber.runtime.io.ClasspathResourceLoader.instantiateSubclasses(ClasspathResourceLoader.java:56)
	at cucumber.runtime.Runtime.loadBackends(Runtime.java:81)
	at cucumber.runtime.Runtime.<init>(Runtime.java:61)
	at com.testng.annotation.AbstractCucumberTest.run(AbstractCucumberTest.java:68)
	at com.testng.annotation.AbstractCucumberTest.run(AbstractCucumberTest.java:27)
	at com.test.login.LoginTest.loginWithGuestAccount(LoginTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at cucumber.runtime.io.ClasspathResourceLoader.newInstance(ClasspathResourceLoader.java:74)
	... 30 more
Caused by: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at cucumber.runtime.io.ClasspathResourceLoader.newInstance(ClasspathResourceLoader.java:74)
	at cucumber.runtime.io.ClasspathResourceLoader.instantiateSubclasses(ClasspathResourceLoader.java:56)
	at cucumber.runtime.io.ClasspathResourceLoader.instantiateExactlyOneSubclass(ClasspathResourceLoader.java:42)
	at cucumber.runtime.java.JavaBackend.loadObjectFactory(JavaBackend.java:43)
	at cucumber.runtime.java.JavaBackend.<init>(JavaBackend.java:31)
	... 35 more
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [cucumber.xml]; nested exception is java.io.FileNotFoundException: class path resource [cucumber.xml] cannot be opened because it does not exist
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:341)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:243)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:127)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:93)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:131)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:530)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:444)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at cucumber.runtime.java.spring.SpringFactory.<clinit>(SpringFactory.java:42)
	... 44 more
Caused by: java.io.FileNotFoundException: class path resource [cucumber.xml] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:157)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:328)
	... 57 more

===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 6 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@156e1ed: 13 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@b69c85: 27 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@1ba229e: 8 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@74bff8: 30 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@11e1a8e: 4 ms

**Comment by igorvsd** [comment]
do you have sample code in public access to try to find the problem ?

**Comment by ramyaw** [comment]
Hi,

Sorry for delayed reply. Please find the project attached.
